import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Material-derived design tokens (from Stitch export DESIGN.md)
        'surface-container-low': '#1b1b1e',
        'on-tertiary-fixed': '#311400',
        tertiary: '#ffb786',
        'outline-variant': '#424754',
        error: '#ffb4ab',
        'on-secondary-fixed': '#1b1b1d',
        'secondary-container': '#474649',
        'secondary-fixed-dim': '#c8c6c8',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary-container': '#461f00',
        'on-secondary-container': '#b7b4b7',
        'error-container': '#93000a',
        'on-error': '#690005',
        'primary-fixed': '#d8e2ff',
        'on-primary': '#002e6a',
        'on-background': '#e4e1e6',
        'tertiary-container': '#df7412',
        'on-secondary': '#303032',
        background: '#131316',
        'surface-bright': '#39393c',
        'inverse-primary': '#005ac2',
        'secondary-fixed': '#e5e1e4',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#502400',
        secondary: '#c8c6c8',
        'on-primary-container': '#00285d',
        'on-surface': '#e4e1e6',
        'primary-container': '#4d8eff',
        primary: '#adc6ff',
        'tertiary-fixed': '#ffdcc6',
        'on-secondary-fixed-variant': '#474649',
        'surface-container-high': '#2a2a2d',
        'surface-tint': '#adc6ff',
        'surface-container-lowest': '#0e0e11',
        'on-primary-fixed-variant': '#004395',
        'surface-container-highest': '#353438',
        outline: '#8c909f',
        'surface-container': '#1f1f22',
        surface: '#09090b',
        'primary-fixed-dim': '#adc6ff',
        'surface-variant': '#353438',
        'inverse-surface': '#e4e1e6',
        'on-surface-variant': '#c2c6d6',
        'inverse-on-surface': '#303033',
        'on-primary-fixed': '#001a42',
        'surface-dim': '#131316',
        'on-tertiary-fixed-variant': '#723600',
        'brand-accent': '#3B82F6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1200px',
        'margin-mobile': '20px',
        // Section rhythm tightened from the Stitch export's 80px/160px —
        // large gaps were the biggest contributor to the "oversized" feel.
        'section-gap-md': '48px',
        'element-gap': '12px',
        'section-gap-lg': '80px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        code: ['"JetBrains Mono"', 'monospace'],
        'display-xl': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'display-xl-mobile': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
      },
      // Type scale tightened roughly 25-30% across the board from the Stitch
      // export's values (e.g. display-xl 72px -> 52px, body-lg 18px -> 16px)
      // so headings and copy read at a normal, comfortable size on screen.
      fontSize: {
        'headline-lg': ['34px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['26px', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '600' }],
        code: ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-xl': ['52px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-xl-mobile': ['34px', { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
